# Generated by Django 3.0.8 on 2020-07-04 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Mobile Number')),
                ('mobile_number_verify', models.BooleanField(default=False, verbose_name='Mobile number verify')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='User Name')),
                ('accepting_terms', models.BooleanField(default=False, verbose_name='Terms & Condition')),
                ('device_id', models.CharField(max_length=40, verbose_name='Device id')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About me')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=20, verbose_name='Gender')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
