# Generated by Django 3.0.8 on 2020-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='country Code'),
        ),
    ]
