# Generated by Django 3.0.8 on 2020-07-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Video Description'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserVideosAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='User likes')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='User comment of video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('commented_or_like_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_id', to='app.UserVideo')),
            ],
            options={
                'verbose_name_plural': 'Videos Comment',
            },
        ),
        migrations.CreateModel(
            name='UserCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='User comment of video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='app.UserVideosAction')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Videos Comment Reply',
            },
        ),
    ]
