# Generated by Django 3.0.8 on 2020-07-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200704_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentreply',
            name='commented_by',
        ),
        migrations.AddField(
            model_name='usercommentreply',
            name='reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserVideosCommentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='User comment of video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by_user', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_on_video', to='app.UserVideo')),
            ],
            options={
                'verbose_name_plural': 'Videos Comment',
            },
        ),
        migrations.CreateModel(
            name='UserVideoLikeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='User likes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_user', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='app.UserVideo')),
            ],
            options={
                'verbose_name_plural': 'Videos likes',
            },
        ),
        migrations.AlterField(
            model_name='usercommentreply',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='app.UserVideosCommentAction'),
        ),
        migrations.DeleteModel(
            name='UserVideosAction',
        ),
    ]
