# Generated by Django 3.0.8 on 2020-07-05 05:04

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200704_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
