# Generated by Django 3.0.8 on 2020-07-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_myusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='image'),
        ),
    ]
