# Generated by Django 3.0.8 on 2020-07-09 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200707_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='type_of_Account',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20, verbose_name='Type of Account'),
        ),
        migrations.CreateModel(
            name='UserFollowingOrFollwed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_request', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Approved', max_length=20, verbose_name='Type of Request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL)),
                ('following_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Account Following or Followed User',
            },
        ),
    ]
