# Generated by Django 3.0.8 on 2020-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200708_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='Views_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Views Count'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='User Videos'),
        ),
    ]
