# Generated by Django 3.0.8 on 2020-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200712_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='type_of_video',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20, verbose_name='Type of video'),
        ),
    ]
