# Generated by Django 3.0.8 on 2020-07-18 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_uservideo_type_of_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercommentreply',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Videos Comment Reply'},
        ),
        migrations.AlterModelOptions(
            name='userfollowingorfollwed',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Account Following or Followed User'},
        ),
        migrations.AlterModelOptions(
            name='uservideo',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'User Videos'},
        ),
        migrations.AlterModelOptions(
            name='uservideolikeaction',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Videos likes'},
        ),
        migrations.AlterModelOptions(
            name='uservideoscommentaction',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Videos Comment'},
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myusers',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='OTP'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Notification description')),
                ('seen', models.BooleanField(default=False, verbose_name='Notification seen')),
                ('type_of_notification', models.CharField(choices=[('Comment', 'Comment'), ('Like', 'Like'), ('Follow Request', 'Follow Request'), ('Follow Approve', 'Follow Approve'), ('Comment Reply', 'Comment Reply'), ('Dislike', 'Dislike'), ('Following', 'Following')], max_length=50, verbose_name='Type of Notification')),
                ('type_of_notification_id', models.IntegerField(verbose_name='Type notification id')),
                ('read', models.BooleanField(default=False, verbose_name='Notification read')),
                ('is_clear', models.BooleanField(default=False, verbose_name='Clear Notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification',
                'ordering': ('-created_at',),
            },
        ),
    ]
