# Generated by Django 3.0.8 on 2020-07-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_usernewtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='dislike_count',
            field=models.BigIntegerField(default=0, verbose_name='Total Dislike Count'),
        ),
        migrations.AlterField(
            model_name='usernewtoken',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='Views_count',
            field=models.BigIntegerField(default=0, verbose_name='Total Views Count'),
        ),
    ]
