# Generated by Django 3.0.8 on 2020-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200720_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideolikeaction',
            name='like',
            field=models.BooleanField(default=True, verbose_name='User likes'),
        ),
    ]
