# Generated by Django 3.0.8 on 2020-07-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200720_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='dislike_count',
        ),
        migrations.CreateModel(
            name='UserVideoDislikeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=True, verbose_name='User dislikes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('disliked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_by_user', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_video', to='app.UserVideo')),
            ],
            options={
                'verbose_name_plural': 'Videos Dislikes',
                'ordering': ('-created_at',),
            },
        ),
    ]
