# Generated by Django 3.0.8 on 2020-07-20 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200720_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\\.[a-zA-Z]+$', 'Email must contain at least one @ and .')], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Mobile Number'),
        ),
    ]
