# Generated by Django 3.0.8 on 2020-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200720_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='device_type',
            field=models.CharField(choices=[('Ios', 'Ios'), ('Android', 'Android')], default='Android', max_length=20, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='social_type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google')], default='Google', max_length=30, verbose_name='Social Type'),
        ),
    ]
