# Generated by Django 3.0.8 on 2020-07-22 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200721_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='video_tag',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Video tag'),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='video_title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Video Title'),
        ),
        migrations.CreateModel(
            name='videoAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.TextField(verbose_name='Video voice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_video_Audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Videos Audio',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='uservideo',
            name='video_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_audio', to='app.videoAudio'),
        ),
    ]
