# Generated by Django 3.0.8 on 2020-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_adminchats_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='User is online'),
        ),
    ]
