# Generated by Django 3.0.8 on 2020-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200722_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='device_id',
            field=models.TextField(max_length=1000, verbose_name='Device id'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='user_name',
            field=models.TextField(unique=True, verbose_name='User Name'),
        ),
    ]
