# Generated by Django 3.0.8 on 2020-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200722_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
