# Generated by Django 2.2.4 on 2020-07-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_sharevideo_share_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coin', models.IntegerField(verbose_name='User coin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User wallet Detail',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Payment order id')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment id')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('payment_capture', models.BooleanField(default=False, verbose_name='Payment capture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverpayment', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderpayment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User payment Detail',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, verbose_name='user card Unique id')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('card_network', models.CharField(max_length=100, verbose_name='Card Network')),
                ('card_expiry_date', models.CharField(max_length=10, verbose_name='Card Expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Card Detail',
                'ordering': ('created_at',),
            },
        ),
    ]
