# Generated by Django 2.2.4 on 2020-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_carddetail_paymentdetail_walletdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='card_last4_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Card last 4 digit'),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='crad_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Holder name'),
        ),
    ]
