# Generated by Django 2.2.4 on 2020-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200726_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='order_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Attempted', 'Attempted'), ('Paid', 'Paid')], default='Created', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_attempts',
            field=models.IntegerField(default=0, verbose_name='Payment attempts on particular order id'),
        ),
    ]
