# Generated by Django 2.2.4 on 2020-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200726_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='order_currancy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='order currancy'),
        ),
    ]
