# Generated by Django 2.2.4 on 2020-07-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_paymentdetail_order_currancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='order_currancy',
            new_name='order_currency',
        ),
    ]
