# Generated by Django 2.2.4 on 2020-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200726_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='type_of_payment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type of payment'),
        ),
    ]
