# Generated by Django 2.2.4 on 2020-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_paymentdetail_type_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Payment signature'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_verify',
            field=models.BooleanField(default=False, verbose_name='Verify payment signature'),
        ),
    ]
