# Generated by Django 2.2.4 on 2020-08-02 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200801_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdetail',
            name='type_of_coin',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('My Collection', 'My Collection')], default='Wallet', max_length=20, verbose_name='Type of coin collection'),
        ),
        migrations.CreateModel(
            name='CoinSharingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(verbose_name='Sharing coin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coin Sharing History',
                'ordering': ('created_at',),
            },
        ),
    ]
