# Generated by Django 2.2.4 on 2020-08-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200802_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinsharinghistory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Coin Sharing History'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'User payment Detail'},
        ),
    ]
